const LawyerList = [
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "3",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي مازن عصام الدين",
    rate: "5",
    speciality: "مدنى",
    vezita: "300",
    address: "المقطم",
    visitors: "150",
    experiance: "10",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "5",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "1",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "4",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "2",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "3",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "4",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "5",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
    visitors: "150",
    experiance: "7",
  },
];

export default LawyerList;
