const LawyerList = [
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "3",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "4",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "5",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "3",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "4",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "5",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "3",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "4",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
  {
    id: new Date().toISOString + Math.random().toString(),
    name: "المحامي عبدالكريم غفار",
    rate: "5",
    speciality: "جنائي",
    vezita: "150",
    address: "وسط البلد",
  },
];
export default LawyerList;
